42_inventory_management/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from inventory_management_app import views
from django.conf import settings


urlpatterns = [
    url(r'^inventory_management_app/admin/', include(admin.site.urls), name="admin"),


    url(r'^inventory_management_app/', include("inventory_management_app.urls"), name="inventory_management_app"),


    # url(r'^static/(?P.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),

    # url(r'^$', login_required(views.dashboard.as_view()), name = 'dashboard'),

]

inventory_management_app/urls.py
from django.conf.urls import url
from inventory_management_app import views
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from inventory_management_app.forms import CustomAuthForm





# Template Tagging
app_name = 'inventory_management_app'





urlpatterns = [


    # url(r'^login/$', auth_views.LoginView.as_view(),name = 'login'),

    url(r'^login/$', auth_views.login, name='login', kwargs={"authentication_form":CustomAuthForm}),





	url(r'^logout/$', auth_views.LogoutView.as_view(), name = 'logout'),



	# url(r'^dashboard', login_required(views.dashboard.as_view()), name = 'dashboard'),
	url(r'^all_assets', login_required(views.all_assets.as_view()), name = 'all_assets'),

	# url(r'^assets_by_project', login_required(views.dashboard.as_view()), name = 'assets_by_project'),


	url(r'^dashboard', views.dashboard, name = 'dashboard'),
	url(r'^assets_by_project', views.assets_by_project, name = 'assets_by_project'),


    url(r'^project_search_results/(?P<project_query>\D+)/$', views.project_search_results, name = 'project_search_results'),




	url(r'^manage_assets', views.manage_assets, name = 'manage_assets'),
	url(r'^search_results', views.search_results, name = 'search_results'),



	url(r'^assets_by_location', views.assets_by_location, name = 'assets_by_location'),
	url(r'^location_search_results/(?P<location_query>\D+)/$', views.location_search_results, name = 'location_search_results'),




    ]



    # 	url(r'^assets_by_project', login_required(views.dashboard.as_view()), name = 'assets_by_project'),

inventory_management_app/models.py
from django.db import models
from simple_history.models import HistoricalRecords
from django.contrib.auth.models import User

# Create your models here.









class Project(models.Model):
    project_number = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    project_name = models.CharField(max_length=255, blank=False, null=True)
    project_date = models.DateTimeField(blank=True, null=True)

    project_manager = models.ForeignKey(User)


    history = HistoricalRecords()


    class Meta:
        managed = True
        db_table = 'Project'
        ordering = ['project_number']

    def __str__(self):
        return self.project_name





class Location(models.Model):
    def __str__(self):
        return "Room %s, Shelf %s, Section %d" %(self.loc_room, self.loc_shelf, self.loc_section)

    loc_room = models.CharField(max_length=20, blank=True, null=True)
    loc_section = models.IntegerField(blank=True, null=True)
    loc_shelf = models.CharField(max_length=4, blank=True, null=True)
    loc_date = models.DateTimeField(blank=True, null=True)

    #what is loc_date for? Name it after its function rather than its type
    #'loc' prefix is unncecesery

    history = HistoricalRecords()

    class Meta:
        managed = True
        db_table = 'Location'
        ordering = ["loc_room", "loc_shelf", "loc_section"]







class Box(models.Model):
    def __str__(self):
        return "Project: %s, Content: '%s', Location: %s" %(self.project_assigned_to, self.box_contents, self.Location)


    box_store_date = models.DateTimeField(blank=True, null=True)
    box_review_date = models.DateTimeField(blank=True, null=True)
    box_contents = models.CharField(max_length=300, blank=True, null=True) #May want to change this and add a 'items' class?
    box_on_loan = models.BooleanField(default=False)
    box_return_date = models.DateTimeField(blank=True, null=True)

    project_assigned_to = models.ForeignKey('Project', null=True)
    Location = models.ForeignKey('Location', null=True)

    #Whats the purpose of on loan, return date - how does this work? Are boxes assigend to another porject for this period? Return date is ecpected or actual return date?
    #Needs database normalization, remove redundancies and contradictions
    #Read about dependancies
    #Understand the processes in the company and how the database will be used
    #Change box_contents to TextField and remove 'max_length'


    history = HistoricalRecords()


    class Meta:
        managed = True
        db_table = 'Box'
        ordering = ["Location", "project_assigned_to"]





class UserQueryHistory(models.Model):
    user = models.ForeignKey(User)
    query = models.CharField(max_length=300, blank=True, null=True)
    date_searched = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = True
        db_table = 'User_Query_History'

    def __str__(self):
        return "User: %s, Query: '%s', Date: %s" %(self.user, self.query, self.date_searched)

inventory_management_app/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput


class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class':'validate','placeholder': 'Email'}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Password'}))


    # def __init__(self, *args, **kwargs):
    #     self.error_messages['invalid_login'] = 'Custom error'
    #     super().__init__(*args, **kwargs)

inventory_management_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView
from django.db.models import Q
from inventory_management_app.models import Project, Location, Box, UserQueryHistory
from inventory_management_app import models

# from django.template import RequestContext

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout

import datetime

from django.db.models import Count

# from .forms import LoginForm

from django.contrib import messages











def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                auth_login(request, user)
                return redirect('index')
        else:
            messages.error(request,'username or password not correct')
            return redirect('login')

    else:
        form = AuthenticationForm()
    return render(request, 'todo/login.html', {'form': form})




from django.contrib.auth import authenticate, login
#@login_required
def dashboard(request):
    user = authenticate(username='demo', password='demodemo')
    login(request, user)
    queries = UserQueryHistory.objects.filter(user=user).order_by('-date_searched')[:7]

    project_data = Project.objects.exclude(box__isnull=True)
    project_data_full = Project.objects.all()


    # box_content_history = Box.history.filter(history_type='-').order_by('-history_date')

    box_content_history = Box.history.all().order_by('-history_date')



    number_of_projects = Project.objects.exclude(box__isnull=True)

    location_data = Location.objects.values('loc_room').distinct()

    box_data = Box.objects.all()







    Vacant_location_data = list(Location.objects.values('loc_room'
     ).filter(box__isnull=True).annotate(nempty=Count('id')).order_by('loc_room'))



    Occupied_location_data = list(Location.objects.values('loc_room'
    ).filter(box__isnull=False).annotate(nempty=Count('id')).order_by('loc_room'))


    if Occupied_location_data:
        for i, vacant in enumerate(Vacant_location_data):
            vacant['occupied'] = Occupied_location_data[i]['nempty']



    return render(request, 'inventory_management_app/dashboard.html', {"queries":queries,
                                                        "project_data":project_data,
                                                        "box_content_history":box_content_history,
                                                        "number_of_projects":number_of_projects,
                                                        "box_data":box_data,
                                                        "location_data":location_data,
                                                        "Vacant_location_data":Vacant_location_data,
                                                        "Occupied_location_data":Occupied_location_data,})









class all_assets(TemplateView):
    template_name = 'inventory_management_app/all_assets.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['box_data'] = Box.objects.all()
        return context

#Transfer to class ListView for above



@login_required
def manage_assets(request):
    return render(request, admin_index)



"""
class assets_by_Project(ListView):
    context_object_name = 'Project_data'
    model = models.Project




"""
@login_required
def assets_by_project(request):
    project_data = Project.objects.all()
    return render(request, 'inventory_management_app/assets_by_project.html', { "project_data":project_data })

##Transfer to class ListView for above






@login_required
def project_search_results(request, project_query):
    query = project_query
    results = Box.objects.filter(Q(project_assigned_to__project_name__icontains=query))
    return render(request, 'inventory_management_app/project_search_results.html', {'query':query,'results':results})

#Transfer to class ListView for above


@login_required
def assets_by_location(request):
    location_data = Location.objects.values('loc_room').distinct('loc_room')
    return render(request, 'inventory_management_app/assets_by_location.html', {"location_data":location_data})


@login_required
def location_search_results(request, location_query):
    query = location_query
    results = Box.objects.filter(Location__loc_room__icontains=query)
    return render(request, 'inventory_management_app/location_search_results.html', {'query':query,'results':results})




@login_required
def search_results(request):
    query = request.GET.get('q')
    results = Box.objects.filter(box_contents__icontains=query)
    UserQueryHistory.objects.create(user=request.user, query=query)

    return render(request, 'inventory_management_app/search_results.html', {"results":results})


















@login_required
def user_log_off(request):
    my_dict = {'insert_me': 'hello, I am from view.py. THIS IS A TEST'}
    return render(request, 'inventory_management_app/user_log_off.html' , context = my_dict)

templates/inventory_management_app/all_assets.html
<!DOCTYPE html>

{% extends "inventory_management_app/inventory_management_app_base.html" %}

  {% block body_block %}

  {% block title %} All Assets {% endblock %}



  <!------------ Scrolling Table ----------->

  <script>


  $(document).ready( function () {
  $('#list_assets_datatable').DataTable({

  "scrollY": "81vh",
  "scrollX": "false",
  "scrollCollapse": true,
  "paging": false,
  "sDom": "ltipr",

  "bAutoWidth": false,


  });
   });
  </script>

<div class="container-fluid">

  <div class="col-sm-12">


    <div class="dtOne">



        <table id="list_assets_datatable" class = "display">

            <thead>
                <tr>
                    <th>Assets</th>
                    <th>Project</th>
                    <th>Room</th>
                    <th>Section</th>
                    <th>Shelf</th>
                </tr>
            </thead>

            <tbody>

              {% for item in box_data %}


                <tr>

                    <td>{{ item.box_contents }}</td>
                    <td>{{ item.project_assigned_to }}</td>
                    <td>{{ item.Location.loc_room }}</td>
                    <td>{{ item.Location.loc_section }}</td>
                    <td>{{ item.Location.loc_shelf }}</td>

                </tr>

                {% endfor %}


            </tbody>

        </table>
      </div>


        </div>

      </div>










  {% endblock %}

templates/inventory_management_app/assets_by_location.html
<!DOCTYPE html>

{% extends "inventory_management_app/inventory_management_app_base.html" %}

{% block title %} Assets by Location {% endblock %}



  {% block body_block %}




  <div class="container-fluid">


  <div style="overflow-y:auto; height:100vh; width:81vw">
  <div class="row">

  {% for item in location_data %}

  <div class="col-sm-4" >
    <a href="location_search_results/{{item.loc_room}}">
      <div class="project_button">




    <span>
        <h1>Room {{ item.loc_room }}</h1>
    </span>




      </div>
    </a>
  </div>

  {% endfor %}


  </div>
  </div>
</div>

  {% endblock %}

templates/inventory_management_app/assets_by_project.html
<!DOCTYPE html>

{% extends "inventory_management_app/inventory_management_app_base.html" %}


{% block title %} Assets by Project {% endblock %}



  {% block body_block %}

<div class="container-fluid">
<div id="viewable_area" class="col-sm-9">
<div style="overflow-y:auto; height:100vh; width:81vw">
<div class="row">

{% for item in project_data %}

<div class="col-sm-4" >
  <a href="project_search_results/{{item.project_name}}">
    <div class="project_button">



  <span>
      <h1>{{ item.project_name }}</h1>
      <h3>{{ item.project_manager.get_full_name }}</h3>
  </span>




    </div>
  </a>
</div>

{% endfor %}
</div>
</div>
</div>
</div>

  {% endblock %}

templates/inventory_management_app/dashboard.html
<!DOCTYPE html>

{% extends "inventory_management_app/inventory_management_app_base.html" %}

{% block title %} Dashboard {% endblock %}



  {% block body_block %}

  <!-- <div class="row">
    <div id="extended_margin" class="col-lg-2">
    </div> -->

<div class="container-fluid">
<div id="dashboard_margin">

  <div class="row">



    <div class="row">

      <div class="col-sm-2" >
        <div class="recent_queries">
        <h3>RECENT QUERIES</h3>
        {% for item in queries %}
        <a class="recent_queries_list" href="{% url 'inventory_management_app:search_results' %}?q={{item.query}}">"{{ item.query }}"</a>
        <br>
        {% endfor %}
        </div>
      </div>

        <div class="row">
          <div class="col-sm-1" >

                <div class="row">
                <div class="col-sm-1 col-md-1 col-lg-1 col-xl-1" >
                  <div class="dashboard_small_box">
                    <h3>ACTIVE PROJECTS</h3>

                    <h2>{{ number_of_projects.count }}</h2>

                  </div>
                </div>
                </div>


                <div class="row">
                <div class="col-sm-1" >
                  <div class="dashboard_small_box">
                    <h3>TOTAL BOXES</h3>
                    <h2> {{ box_data.count }} </h2>
                  </div>
                </div>
                </div>

              </div>
            </div>

        <div class="row">



<!-- Pie chart -->

          <div class="col-sm-2" >
            <div class="pie_chart">
          <script type="text/javascript">

          $(function () {
            var my_pie_chart = Highcharts.chart('pie_container', {
              chart: {
                type: 'pie',
                options3d: {
                  enabled: true,
                  alpha: 70
                }
                },
                exporting: { enabled: false },

                title: {
                    text: 'Boxes per project',
                    align: 'left',
                  },
                  plotOptions: {
                    pie: {
                      innerSize: 120,
                      depth: 15,
                    },


                  },
                  series: [{
                    name: 'Boxes Assigned',
                    data: [
                      {% for item in project_data %}

                      ['{{item.project_name}}', {{item.box_set.count}}],

                      {% endfor %}

                    ]
                  }]
                });
              });


                </script>



            <div id="pie_container" style="width:100%; height:45vh;">
            </div>
          </div>
          </div>

        </div>


    </div>






          <div class="row">


<!-- Free Shelf Space Dashboard Widget -->




              <div class="col-sm-5">

                <div class="dashboard_shelf_space_widget">

                <script type="text/javascript">
                $(function () {
                  var free_space_chart =

                  Highcharts.chart('free_space_chart', {




                    chart: {
                        type: 'column'
                    },
                    title: {
                        text: 'Free Shelf Space',
                        align: 'left',

                    },
                    subtitle: {
                        text: 'Click columns for breakdown by room',
                        align: 'left',

                    },
                    xAxis: {
                        type: 'category'
                    },
                    yAxis: {
                        title: {
                            text: 'Number of free spaces'
                        }

                    },

                    exporting: { enabled: false },


                    legend: {
                        enabled: false
                    },



                    colors: [
                      '#212a1e',


                      ],






                    plotOptions: {
                        series: {
                            borderWidth: 0,
                            dataLabels: {
                                enabled: true,
                                format: '{point.y:.0f}',

                            }
                        }
                    },

                    credits: { enabled: false },
                    tooltip: { enabled: false },


                    "series": [
                        {
                            "name": "Room",
                            "colorByPoint": true,
                            // "colors": 'red',
                            "data": [

                              {% for each_space in Vacant_location_data %}

                              {
                                "name": "Room {{ each_space.loc_room }}",
                                "y": {{ each_space.nempty }},
                                "drilldown": "{{ each_space.loc_room }}"
                              },

                              {% endfor %}

                            ]
                        }
                    ],
                    "drilldown": {
                          drillUpButton: {
                            relativeTo: 'spacingBox',
                            position: {
                              y: 0,
                              x: 0
                                    },
                            theme: {
                                  fill: '#cecece',
                                  'stroke-width': 1,
                                  stroke: 'silver',
                                  r: 0,
                                  states: {
                                      hover: {
                                          fill: '#a0a0a0',
                                          stroke: '#a0a0a0'
                                        },
                                        select: {
                                          stroke: '#a0a0a0',
                                          fill: '#a0a0a0'
                                }
                            }}},


                        "series": [

                          {% for each_space in Vacant_location_data %}


                            {
                                "name": "{{ each_space.loc_room }}",
                                "id": "{{ each_space.loc_room }}",

                                "data":[
                                    {
                                        name: "Free space",
                                        y: {{ each_space.nempty }},
                                        color:'#212a1e'

                                    },

                                    {
                                        name: "Occupied Space",
                                        y: {{ each_space.occupied }},
                                        color: '#633333'
                                    },


                                ]







                            },

                            {% endfor %}


                        ]
                    }






                    })
                    console.log('free_space_chart ', free_space_chart);

                    });

                    </script>




                <div id="free_space_chart">


                      <div>



                      </div>





                    </div>




                  </div>
                  </div>

              </div>



<!-- Asset Changes Dashboard Widget -->

              <div class="col-sm-5">

                <script>
                $(document).ready(function(){
                        $('#asset_changes_table').find('tr:contains("Created")').css('background-color','#212B1E');
                        $('#asset_changes_table').find('tr:contains("Deleted")').css('background-color','#472727');
                        $('#asset_changes_table').find('tr:contains("Changed")').css('background-color','#4C462A');


                });
                </script>





                <div class="asset_changes_widget">

                  <!-- <h3>ASSET CHANGES</h3> -->



                    <table id="asset_changes_table">

                      <colgroup>
                        <col style="width:18vw">
                        <col style="width:18vw">
                        <col style="width:70vw">
                      </colgroup>

                    <thead>
                        <tr>
                          <th>CHANGES MADE</th>
                          <th>PROJECT</th>
                          <th>BOX CONTENTS</th>
                        </tr>
                    </thead>

                    <tbody>

                      {% for item in box_content_history %}


                        <tr>

                          <td>{{ item.get_history_type_display }}</td>
                          <td>{{ item.project_assigned_to }}</td>
                          <td>{{ item.box_contents }}</td>

                        </tr>

                        {% endfor %}


                    </tbody>

                </table>
              </div>











                    </div>
                    </div>




          </div>
      </div>
    </div>



  </div>







  {% endblock %}

templates/inventory_management_app/inventory_management_app_base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <!-- My Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Maven+Pro" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Unica+One" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Exo:100,200,300,400" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">


    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

    <!-- Jquery-->
    <script   src="https://code.jquery.com/jquery-3.3.1.min.js"   integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="   crossorigin="anonymous"></script>

    <!-- Datatables CDN-->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script src="https://code.highcharts.com/highcharts.src.js"></script>



    <!-- Highcharts-->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/highcharts-3d.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>



    <script src="https://code.highcharts.com/modules/data.js"></script>
    <script src="https://code.highcharts.com/modules/drilldown.js"></script>


    <!-- My Custom JS -->
    <script src="{% static 'js/inventory_management_app.js' %}"></script>
    <!-- My Custom CSS -->
    <link rel="stylesheet" href= "{% static "css/base.css" %}" >



    <title>{% block title %}My title{% endblock %}</title>

</head>









<body>

    <div class="wrapper">

        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
              
              <img src="{% static 'images/42_technology.svg'%}" alt="" width="25vw" height="25vh">
              <h4>Inventory Managment</h4>
              <h4 style="font-size: 1em;">DEMO VERSION</h4>

            </div>

            <ul class="list-unstyled components">


                <li>

                  <form class="search-button" action= "{% url 'inventory_management_app:search_results' %}" method="get">
                    <label for="form-control">
                    <input class="form-control" name = "q" value="{{request.GET.q}}" placeholder="Enter asset name here">
                    </label>

                    <br>


                    <button id = "search-button" class="btn btn-dark" type="submit"> Submit </button>

                  </ul>


                  </form>


                  <ul class="list-unstyled components">

                </li>


                  <li>
                <a href="{% url 'inventory_management_app:dashboard' %}">Dashboard</a>
                  </li>

                  </ul>


              <ul class="list-unstyled components">


                <li>
                    <a href="{% url 'inventory_management_app:all_assets' %}">All Assets</a>
                </li>

                <li>
                    <a href="{% url 'inventory_management_app:assets_by_project' %}">Assets by Project</a>
                </li>


                <li>
                  <a href="{% url 'inventory_management_app:assets_by_location' %}">Assets by Location</a>

                </li>


            </ul>




            <ul class="list-unstyled components">

              <li>
                <a href="{% url 'admin:index' %}">Manage Assets</a>
              </li>



              <li>
                <!-- <a href="{% url 'inventory_management_app:logout' %}">Logout</a> -->
                <a href="https://www.developwithtom.com/work">Logout</a>

              </li>

            </ul>


        </nav>


        <!-- Page Content  -->



    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>








<!-------- Column behind sidebar  --------->

<!-- <div class="row">
  <div id="extended_margin" class="col-lg-2">
  </div> -->


<!-------------------------------------------------->

<!--------------- Template Inheritance ------------->




  {% block body_block %}
<!-- anything outside of this will be inherited -->
  {% endblock %}







</body>

</html>

templates/inventory_management_app/location_search_results.html
<!DOCTYPE html>

{% extends "inventory_management_app/inventory_management_app_base.html" %}


{% block title %} Assets by Location Search Results {% endblock %}


  {% block body_block %}




<!------------ Scrolling Table ----------->

<script>
$(document).ready( function () {
$('#list_assets_datatable').DataTable({

"scrollY": "81vh",
"scrollX": "false",
"scrollCollapse": true,
"paging": false,
"sDom": "ltipr",

"bAutoWidth": false,
  });
});
</script>

<div class="container-fluid">
<div class="col-sm-12">


<div class="dtOne">



      <table id="list_assets_datatable" class = "display">

          <thead>
              <tr>
                  <th>Assets</th>
                  <th>Project</th>
                  <th>Room</th>
                  <th>Section</th>
                  <th>Shelf</th>
              </tr>
          </thead>

          <tbody>

            {% for item in results %}


              <tr>

                  <td>{{ item.box_contents }}</td>
                  <td>{{ item.project_assigned_to }}</td>
                  <td>{{ item.Location.loc_room }}</td>
                  <td>{{ item.Location.loc_section }}</td>
                  <td>{{ item.Location.loc_shelf }}</td>

              </tr>

              {% endfor %}


          </tbody>

      </table>


      </div>
      </div>
      </div>













  {% endblock %}

templates/inventory_management_app/manage_assets.html
<!DOCTYPE html>

{% extends "inventory_management_app/inventory_management_app_base.html" %}

  {% block body_block %}

  {% endblock %}